#!/usr/bin/env bash

module_label=$'\x02'"["$'\x032'"Shorten"$'\x0f\x02'"]"$'\x0f'

$(help.hook "$(fantasy.char)shorten [url] -- Shortens URL for you using sCURL.") > /dev/null

function shorten() {
        #Using fantasy omits the original fantasy word
        longurl=$(echo "$1" | awk '{print $1}')

	if [[ ! $(echo "${longurl}" | grep -E '[http|https]://.*') ]]; then
		msg $(dest) ${module_label}' Error! Scheme missing. Must provide a valid URL to shorten.'
	else
		shorturl=$(curl -sL "http://scurl.tk/api.php?url=${longurl}")
		shorturl=${shorturl//%}
		msg $(dest) ${module_label}" Your shortened url is: ${shorturl}"
	fi
	
}


hook=$(fantasy.hook shorten shorten > /dev/null)
